config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '',path_names: {sign_in: 'login', sign_up: 'register', sign_out: 'logout'}
  resources :portfolios
  get 'angular-item' , to: 'portfolios#angular'
  root to: 'pages#home'
  get 'about', to: 'pages#about'
  get 'contact' ,to: 'pages#contact'
  resources :blogs do 
    member do
      get :toggle_status
    end
  end
end

app/models/blog.rb
class Blog < ApplicationRecord
    enum status: { draft: 0, published: 1 }
    extend FriendlyId
    friendly_id :title, use: :slugged
    validates_presence_of :title, :body
     belongs_to :topic
end
 

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]
  layout "blog"
  access all: [:show, :index], user: {except: [:destroy, :new, :create, :update, :edit] }, site_admin: :all
  # GET /blogs
  # GET /blogs.json
  def index
    @blogs = Blog.page(params[:page]).per(5)
    @page_title = "Blog" 
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format| 
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Blog was successfully destroyed.' }
    end
  end

  def toggle_status
    @blog = Blog.friendly.find(params[:id])
    if @blog.published?
      @blog.status="draft"
      @blog.save
      redirect_to blogs_path

    else
      @blog.status="published"
      @blog.save
      redirect_to blogs_path
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.friendly.find(params[:id])
    end
  # Only allow a list of trusted parameters through.

    def blog_params
      params.require(:blog).permit(:title, :body)
    end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/blogs/_blog.html.erb
<!--<tr>
        <td><%= blog.title %></td>
        <td>Published <%= time_ago_in_words(blog.created_at) %></td>
        <td><%= blog.body %></td>
         <td> <%= link_to  blog.status,toggle_status_blog_path(blog) %> </td>
        <td><%= link_to 'Show', blog %></td>
        <td><%= link_to 'Edit', edit_blog_path(blog) %></td>
        <td><%= link_to 'Destroy', blog, method: :delete, data: { confirm: 'Are you sure?' } %></td>
</tr>
-->
<div class="card mt-3">
  <div class="card-body">
    <div class="card-header h3">
      <%= blog.title  %> <br>
      <small class="h6">Published <%= time_ago_in_words(blog.created_at) %></small>
    </div>
    <div class="card-text">
      <%= blog.body %>
    </div>

    <div class="card-footer text-center">
        <%= link_to  blog.status,toggle_status_blog_path(blog), class: "btn btn-primary mr-3" %>
        <%= link_to 'Show', blog, class: "btn btn-info mr-3"%>
        <%= link_to 'Edit', edit_blog_path(blog) ,class: "btn btn-info mr-3"%>
        <%= link_to 'Destroy', blog, method: :delete, data: { confirm: 'Are you sure?' } , class: "btn btn-danger mr-3"%>
    </div>
  </div>
</div>

app/views/blogs/_form.html.erb
<!--<%= form_with(model: blog, local: true) do |form| %>
  <% if blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
        <% blog.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>
-->

<div class="card bg-light text-dark text-left card-form">
  <div class="card-body">
    <%= form_with(model: blog, local: true) do |form| %>  
     <% if blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
        <% blog.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <form>
    <div>
      <%= form.label :title %>
      <%= form.text_field :title, autofocus: true, class: "form-control form-control-lg" %>
      </div>
      <div  class="mt-3">
        <%= form.label :body %>
        <%= form.text_area :body, cols: "10", rows: "15", class: "form-control form-control-lg"%>
      </div>
    <div class="actions text-right mt-3">
               <%= form.submit  class: "btn rounded-pill btn-success  btn-block w-25 mx-auto " %>
    </div>
    </form>
    <%end%>
  </div>
</div>

app/views/blogs/edit.html.erb
 <div class="col-md-8 blog-main">
 <div class="text-center">
    <h3 class="card-header mb-2 ">Edit blog</h3>
 </div>
<%= render 'form', blog: @blog %>
<div class="text-center mt-3">
    <%= link_to 'Show', @blog, class: 'btn btn-info mr-3 mb-3' %>
    <%= link_to 'Back', blogs_path, class: 'btn btn-dark mb-3' %>
</div>
</div>

app/views/blogs/index.html.erb
<p id="notice"><%= notice %></p>

    <div class="col-md-8 blog-main">
      <div class="d-flex justify-content-between align-items-center border-bottom">
          <h3 class="font-italic ">
            Hello, 
          </h3>
          <%= link_to 'Create New Blog', new_blog_path, class: "rounded-pill btn btn-success mb-3" %>
       </div>
       <div class="d-flex justify-content-center">
        <%= paginate @blogs%>
        </div>
      <%= render @blogs %>
        <div class="d-flex justify-content-center">
          <%= paginate @blogs, class: "text-center"%>
        </div>

    </div><!-- /.blog-main -->


 

app/views/blogs/new.html.erb
<div class="col-md-8 blog-main">
    <div class="text-center">
        <h3 class="card-header mb-2 ">Create new blog</h3>
    </div>
    <%= render 'form', blog: @blog %>

    <div class="text-center mt-3">
        <%= link_to 'Back', blogs_path, class: 'btn btn-dark mb-3' %>
    </div>
</div>

app/views/blogs/show.html.erb
<p id="notice"><%= notice %></p>

<div class="card">
  <div class="card-header">
     <%= @blog.title %>
  </div>
  <div class="card-body">
    <div class="card-text">
      <%= @blog.body %>
    </div>
    <div class="card-footer text-center">
      <%= link_to 'Edit', edit_blog_path(@blog), class: "btn btn-info mr-3 px-5" %> 
      <%= link_to 'Back', blogs_path , class: "btn btn-dark px-5"%>
    </div>
  </div>
</div>
<!--
<p>
  <strong>Title:</strong>
  <%= @blog.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @blog.body %>
</p>

<%= link_to 'Edit', edit_blog_path(@blog) %> |
<%= link_to 'Back', blogs_path %>
-->