config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '',path_names: {sign_in: 'login', sign_up: 'register', sign_out: 'logout'}
  resources :portfolios
  get 'angular-item' , to: 'portfolios#angular'
  root to: 'pages#home'
  get 'about', to: 'pages#about'
  get 'contact' ,to: 'pages#contact'
  resources :blogs do 
    member do
      get :toggle_status
    end
  end
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
    include Placeholder
    has_many :technologies
    accepts_nested_attributes_for :technologies,
                                    reject_if: lambda {|attrs| attrs['name'].blank? }
    validates_presence_of :title, :body, :main_image, :thumb_image
    scope :angular, -> { where(:subtitle => "Angular")}
    # Ex:- scope :active, -> {where(:active => true)}
    after_initialize :set_defaults

    
    def set_defaults
        self.main_image ||= Placeholder.set_image(height: 600,width: 400)
        self.thumb_image ||= Placeholder.set_image(height: 350,width: 200)
    end
    def self.by_position
        order("position ASC")
    end

end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  layout "portfolio"
    def index
        @portfolio_items = Portfolio.by_position
    end

    def angular
      @portfolio_item_angular=Portfolio.angular
    end

   def new
        @portfolio_item =Portfolio.new
        3.times { @portfolio_item.technologies.build }
   end

   def edit 
    @portfolio_item=Portfolio.find(params[:id])
   end

   def show
    @portfolio_item=Portfolio.find(params[:id])
  end
  
  def create
    @portfolio_item = Portfolio.new( params.require(:portfolio).permit(:title, :subtitle, :body, technologies_attributes: [:name]))

    respond_to do |format| 
      if @portfolio_item.save
        format.html { redirect_to portfolios_path, notice: 'portfolio was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    @portfolio_item=Portfolio.find(params[:id])
    respond_to do |format|
      if @portfolio_item.update(portfolio_params)
        format.html { redirect_to portfolios_path, notice: 'Blog was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

 

  def destroy
    @portfolio_item=Portfolio.find(params[:id]) 
    @portfolio_item.destroy

    respond_to do |format|
      format.html { redirect_to portfolios_path, notice: 'portfolio was successfully destroyed.' }
    end 
  end



  def portfolio_params
    params.require(:portfolio).permit(:title, :subtitle, :body)
  end

end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/views/portfolios/_form.html.erb
<!--
<%= form_for(portfolio_item) do |form| %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

    <div class="field">
    <%= form.label :subtitle %>
    <%= form.text_field :subtitle %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <ul>
    <%= form.fields_for :technologies do |technology_form| %>
    <li><%= technology_form.label :name %></li>
    <li><%= technology_form.text_field :name %></li>
    <% end %>
  </ul>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>
-->

<div class="container">
<%= form_for(portfolio_item) do |form| %>

<div class="card bg-light text-center card-form">
   <div class="card-body">
     <form>
      <div class="form-group field">
      <%= form.label :title %>
    <%= form.text_field :title, class: "form-control form-control-lg" %>
      </div>

    <div class="field form-group">
     <%= form.label :subtitle %>
        <%= form.text_field :subtitle ,class: "form-control form-control-lg "%>
  </div>

  <div class="field">
     <%= form.label :body %>
    <%= form.text_area :body,cols: "10", rows: "10", class: "form-control form-control-lg"%>
  </div>

    <h3 class="my-3" >Technology used</h3>

    <%= form.fields_for :technologies do |technology_form| %>

      
  <div class="form-group field">
            <%= technology_form.text_field :name ,class: "form-control form-control-lg" %>
          </div>
    <% end %>
  </ul>

   <div class="actions text-right">
               <%= form.submit  class: "btn rounded-pill btn-success  btn-block w-25 mx-auto btn-outline-dark" %>
   </div>
   </form>
</div>
<div>

<% end %>

</div>

</div>

app/views/portfolios/_portfolio_item.html.erb
  <!-- <p><%= link_to portfolio_item.title,portfolio_path(portfolio_item) %></p>
   
   <p><%= portfolio_item.subtitle%></p>
   
   <p><%= portfolio_item.body%></p>
   
    <%= image_tag portfolio_item.thumb_image if !portfolio_item.thumb_image.nil? %>
   
    <%= link_to 'Edit', edit_portfolio_path(portfolio_item) %><br>
   
    <%= link_to 'Delete', portfolio_path(portfolio_item),method: :delete, data: { confirm: 'Are you sure?' } %>
-->
<div class="col-md-4">
   <div class="card mb-4 shadow-sm">
   <%= image_tag portfolio_item.thumb_image if !portfolio_item.thumb_image.nil? %>
   <div class="card-body">
      <p class="card-title">  <%= link_to portfolio_item.title,portfolio_path(portfolio_item) %> </p>
      <p class="card-subtitle"><%= portfolio_item.subtitle%></p>
   </div>
  </div>
</div>

app/views/portfolios/angular.html.erb
<h1>Angular portfolio item</h1>
<%= link_to 'Creaate new article', new_portfolio_path %>
<% @portfolio_item_angular.each do |portfolio_item| %>
   <p><%= link_to portfolio_item.title,portfolio_path(portfolio_item) %></p>
   <p><%= portfolio_item.subtitle%></p>
   <p><%= portfolio_item.body%></p>
    <%= image_tag portfolio_item.thumb_image if !portfolio_item.thumb_image.nil? %>
    <%= link_to 'Edit', edit_portfolio_path(portfolio_item) %><br>
    <%= link_to 'Delete', portfolio_path(portfolio_item),method: :delete, data: { confirm: 'Are you sure?' } %>
<% end %>

app/views/portfolios/edit.html.erb
<div class="text-center my-3"><h3> Edit portfolio</h2></div>
<%= render 'form', portfolio_item: @portfolio_item %>

app/views/portfolios/index.html.erb
<div class="album py-5 bg-light">
    <div class="container">
      <div class="row">
        <%= render partial: 'portfolio_item', collection: @portfolio_items %>
      </div>
    </div>
</div>

app/views/portfolios/new.html.erb
<div class="text-center my-3"><h3> Create new portfolio</h2></div>
<%= render 'form', portfolio_item: @portfolio_item %>

app/views/portfolios/show.html.erb
<div class="container">
    <div class="row"> 
        <div class="col-md-7">
         <%= image_tag @portfolio_item.main_image%> 
        </div>
        <div class="col-md-5">
            <h1> <%= @portfolio_item.title%> </h1>
            <hr>
            <em> <%= @portfolio_item.subtitle %> </em>
            <hr>

            <h5 class="lead"> <%= @portfolio_item.body %></h3>
        <h3>Technologies used</h3>
        <% @portfolio_item.technologies.each do |t|%>
        <p><%= t.name %></p>
        <% end %>
       
         </div>
    </div>
</div>