config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '',path_names: {sign_in: 'login', sign_up: 'register', sign_out: 'logout'}
  resources :portfolios
  get 'angular-item' , to: 'portfolios#angular'
  root to: 'pages#home'
  get 'about', to: 'pages#about'
  get 'contact' ,to: 'pages#contact'
  resources :blogs do 
    member do
      get :toggle_status
    end
  end
end

app/views/shared/_alerts.html.erb
<% if flash[:alert] %>
    <%= js add_gritter(flash[:notice],  title: "Sun raha hai na tuuuuu!", :sticky => true) %>
    <% elsif flash[:error] %>
    <%= js add_gritter(flash[:error],  title: "Sun raha hai na tuuuuuu!", :sticky => true) %>
<% else %>
    <%= js add_gritter(flash[:notice],  title: "Sun raha hai na tuuuuuu!", :sticky => true) %>
<% end %>

app/views/shared/_application_nav.html.erb
<header class="masthead ">
    <div class="inner">
      <h3 class="masthead-brand">Bhavesh Mishra</h3>
      <nav class="nav nav-masthead justify-content-center">
       <%= link_to 'Home', root_path,class: "nav-link" %> 
       <%= link_to 'Contact', contact_path ,class: "nav-link"%>
       <%= link_to 'About-me', about_path ,class: "nav-link"%>
      <%= link_to 'Blog', blogs_path ,class: "nav-link"%>
      <%= link_to 'Portfolio', portfolios_path ,class: "nav-link"%>
      <%= login_helper 'nav-link' %>
      </nav>
    </div>
</header>

app/views/shared/_blog_nav.html.erb
<div class="d-flex   align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
  <h5 class="my-0 mr-md-auto font-weight-normal">Blogging</h5>
  <nav class="my-2 d-flex  my-md-0 mr-md-3">
       <%= link_to 'Home', root_path, class: "nav-link" %> 
        <%= link_to 'About', about_path, class: "nav-link" %> 
        <%= link_to 'Contact', contact_path, class: "nav-link" %> 
        <%= link_to 'Blog', blogs_path, class: "nav-link" %>
        <%= link_to 'Portfolio', portfolios_path, class: "nav-link" %> 
  </nav>
    <%= login_helper 'btn btn-primary mr-2' %>
</div>

app/views/shared/_nav.html.erb
 <div>
        <div> <%= link_to 'Home', root_path %> </div>
        <div> <%= link_to 'About', about_path %> </div>
        <div> <%= link_to 'Contact', contact_path %> </div>
        <div> <%= link_to 'Blog', blogs_path %> </div>
        <div> <%= link_to 'Portfolio', portfolios_path %> </div>
 </div> 
 